### PR TITLE
Frame cam no bounds

### LINKED ISSUE #489: Frame camera throws out-of-bounds exception
The frame camera model code throws an exception when it is asked to find the sensor position and velocity when the input pixel is a bit outside of the image domain. This is for functions UsgsAstroFrameSensorModel::getSensorPosition() and getSensorVelocity().

This is not desirable behavior. It is possible for a ground point to project into the camera at a pixel outside of the image box. The software should be able to return the sensor position and velocity for such a pixel, which is the same for all pixels anyway, for a frame camera.

This check is not present for linescan cameras, which graciously does the best it can. It clamps the input pixel line to the range of lines it can handle.

Such behavior as for the frame camera is problematic as it requires fixes in software that functions perfectly fine with other camera implementations, including outside of usgscsm.

### PR DESCRIPTION
**Pull request by jrcain-usgs**
- Removed any checks at all for pixel boundary in UsgsAstroFrameSensorModel::getSensorPosition(imageCoord).
- Added a test to check a pixel exceeding the boundary.

Fixes #489 

## Licensing
This project is mostly composed of free and unencumbered software released into the public domain, and we are unlikely to accept contributions that are not also released into the public domain. Somewhere near the top of each file should have these words:

> This work is free and unencumbered software released into the public domain. In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

- [x] I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

### CODE REVIEW

**Comment by chkim-usgs** [comment]
An update to the changelog and it should be good to go.

File: tests/FrameCameraTests.cpp [hunk 1]
```diff
@@ -531,6 +531,11 @@ TEST_F(FrameSensorModelLogging, GetSensorPositionPixel) {
   sensorModel->getSensorPosition(imagePt);
 }
 
+TEST_F(FrameSensorModelLogging, GetSensorPositionPixelExceedsBounds) {
+  csm::ImageCoord imagePt(-1, -1);
+  sensorModel->getSensorPosition(imagePt);
```
Comment (acpaquette) [inline tests/FrameCameraTests.cpp:536]: A slightly better test would be to do a round robin using a pixel that is outside of the image. Basically, run `imageToGround`, get the ground coord, then run `groundToImage` and see what pixel the camera returns

Comment (acpaquette) [reply tests/FrameCameraTests.cpp:536]: After some discussion and digging, the framing camera model doesn't use `getSensorPosition` in the `imageToGround` call so this test can more or less stay as is. It would be a good idea to still check the x, y, z output from `getSensorPosition`

Comment (jrcain-usgs) [reply tests/FrameCameraTests.cpp]: Discussed this with @acpaquette, we decided it would actually be better just to add a check on the position.

**Review by chkim-usgs — APPROVED** [review]
